# Generated by Django 4.2.9 on 2026-06-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['price'], name='idx_course_price'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'is_published'], name='idx_course_inst_pub'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='idx_course_level'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status', 'enrolled_at'], name='idx_enroll_course_stat_date'),
        ),
    ]
